/* Replace with your SQL commands */
-- MySQL Script generated by MySQL Workbench
-- mer. 03 févr. 2021 10:41:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema climbing_crag
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema climbing_crag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `climbing_crag` DEFAULT CHARACTER SET utf8;
USE `climbing_crag`;
-- -----------------------------------------------------
-- Table `climbing_crag`.`crags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing_crag`.`crags` (
  `id` INT NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `exposition` VARCHAR(45) NOT NULL,
  `rocks` VARCHAR(150) NOT NULL,
  `city` VARCHAR(150) NOT NULL,
  `picture` VARCHAR(150) NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `climbing_crag`.`routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing_crag`.`routes` (
  `id` INT NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `multipitch` TINYINT NOT NULL,
  `grade` VARCHAR(45) NOT NULL,
  `done` TINYINT NOT NULL,
  `picture` VARCHAR(150) NULL,
  `Crag_id` INT NOT NULL,
  `length` INT NOT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Routes_Crag_idx` (`Crag_id` ASC) VISIBLE,
  CONSTRAINT `fk_Routes_Crag` FOREIGN KEY (`Crag_id`) REFERENCES `climbing_crag`.`crags` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `climbing_crag`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing_crag`.`users` (
  `id` INT NOT NULL,
  `firstname` VARCHAR(150) NOT NULL,
  `lastname` VARCHAR(150) NOT NULL,
  `mail` VARCHAR(150) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `climbing_crag`.`User_has_Crag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing_crag`.`User_has_Crag` (
  `User_id` INT NOT NULL,
  `Crag_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `Crag_id`),
  INDEX `fk_User_has_Crag_Crag1_idx` (`Crag_id` ASC) VISIBLE,
  INDEX `fk_User_has_Crag_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Crag_User1` FOREIGN KEY (`User_id`) REFERENCES `climbing_crag`.`users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_Crag_Crag1` FOREIGN KEY (`Crag_id`) REFERENCES `climbing_crag`.`crags` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `climbing_crag`.`User_has_Routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing_crag`.`User_has_Routes` (
  `User_id` INT NOT NULL,
  `Routes_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `Routes_id`),
  INDEX `fk_User_has_Routes_Routes1_idx` (`Routes_id` ASC) VISIBLE,
  INDEX `fk_User_has_Routes_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Routes_User1` FOREIGN KEY (`User_id`) REFERENCES `climbing_crag`.`users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_Routes_Routes1` FOREIGN KEY (`Routes_id`) REFERENCES `climbing_crag`.`routes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;